### ISSUE TITLE
placing comment still buggy (sometimes you need to press 5x that its published once)

### ISSUE THREAD

**Issue by marcelinhio** [SocialXNetwork/socialx_react_native#142]
**Describe the bug**
Try to post a comment and wait until its reflected

**To Reproduce**
Post a comment 

**Expected behavior**
See if the comment will be refreshed right away
Or at least after waiting
For me it did not appear even after waiting (just sometimes)

**Screenshots**
See video 
https://drive.google.com/open?id=1zgma9gglBdjX5Tsno6RqPe22YjGOxonB

**Smartphone (please complete the following information):**
Iphone X
Latest iOSD

**Comment by Shadyzpop** [comment]
just to note something here @marcelinhio in the video if you look at the `View x comments` the number increases when you comment on things, the reason why it doesnt show up because the comments on the front of the posts are basically the two most popular and since you just added yours it doesnt appear
