### ISSUE TITLE
Media Info, check why name is not displayed

### ISSUE THREAD

**Issue by ChristBKK** [SocialXNetwork/socialx_react_native#98]
Media Info, check why name is not displayed.

![45718411_2352308661464134_1239276327513620480_n](https://user-images.githubusercontent.com/12375330/48282899-92402880-e48d-11e8-9269-18442299727f.jpg)

**Comment by alexcroitoru95** [comment]
I discussed with @Shadyzpop and @alexsirbu04, and we think it's better to not show any Name Field. This is because we might run into conflicts with users that post an image with same name as others. The option to fix this should be to show only the identifier.jpeg/png/etc, but again this shouldn't be shown to the user, in our opinion.

**Comment by ChristBKK** [comment]
@alexcroitoru95  feel free to erase that field then from the modal.

**Comment by alexcroitoru95** [comment]
@ChristBKK Will do.

**Comment by alexcroitoru95** [comment]
Removed field Name from Media Info Modal.
